"""fix message model

Revision ID: 1a685c5a2b16
Revises: 661fd272ec5a
Create Date: 2025-07-16 14:14:57.198253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a685c5a2b16'
down_revision: Union[str, Sequence[str], None] = '661fd272ec5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_column('messages', 'user_id')
    # ### end Alembic commands ###
