"""Ajout champ user_id dans Message

Revision ID: 383637b23774
Revises: c394fd4b1380
Create Date: 2025-07-16 11:46:12.799591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '383637b23774'
down_revision: Union[str, Sequence[str], None] = 'c394fd4b1380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('messages_interaction_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'interactions', ['interaction_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_interaction_id_fkey'), 'messages', 'interactions', ['interaction_id'], ['id'])
    # ### end Alembic commands ###
