"""fusion user + interaction

Revision ID: 740c8a43efd8
Revises: b7cb403bd750
Create Date: 2025-07-08 01:03:18.797028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '740c8a43efd8'
down_revision: Union[str, Sequence[str], None] = 'b7cb403bd750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('final_answer', sa.String(), nullable=False),
    sa.Column('confiance', sa.Float(), nullable=True),
    sa.Column('clarte', sa.Float(), nullable=True),
    sa.Column('empathie', sa.Float(), nullable=True),
    sa.Column('assertivite', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_id'), 'interactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interactions_id'), table_name='interactions')
    op.drop_table('interactions')
    # ### end Alembic commands ###
