"""Ajout messages (thread) aux interactions

Revision ID: 9b796d3ab38d
Revises: ac00a41edf05
Create Date: 2025-07-15 12:02:02.346473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b796d3ab38d'
down_revision: Union[str, Sequence[str], None] = 'ac00a41edf05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('messages', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('interactions', sa.Column('authenticite', sa.Float(), nullable=True))
    op.add_column('interactions', sa.Column('creativite', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interactions', 'creativite')
    op.drop_column('interactions', 'authenticite')
    op.drop_column('interactions', 'messages')
    # ### end Alembic commands ###
